import PDFDocument from "pdfkit";
import { createWriteStream } from "node:fs";
import { db, firmwareTable, vulnerabilitiesTable, aiReportsTable, scanResultsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { reportPdfPath } from "../lib/paths.js";

export async function generatePdfReport(firmwareId: number): Promise<{ path: string; size: number }> {
  const [fw] = await db.select().from(firmwareTable).where(eq(firmwareTable.id, firmwareId));
  const vulns = await db.select().from(vulnerabilitiesTable).where(eq(vulnerabilitiesTable.firmwareId, firmwareId));
  const [report] = await db.select().from(aiReportsTable).where(eq(aiReportsTable.firmwareId, firmwareId));
  const [scan] = await db.select().from(scanResultsTable).where(eq(scanResultsTable.firmwareId, firmwareId));

  const keyFindings = report ? (JSON.parse(report.keyFindings) as string[]) : [];
  const recommendations = report ? (JSON.parse(report.recommendations) as string[]) : [];

  const outPath = reportPdfPath(firmwareId);

  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const stream = createWriteStream(outPath);

  const finished = new Promise<void>((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
    doc.on("error", reject);
  });

  doc.pipe(stream);

  doc.fontSize(20).text("VIV SCANNER — FIRMWARE SECURITY REPORT", { align: "center" });
  doc.moveDown();

  doc.fontSize(11);
  doc.text(`Firmware: ${fw?.name ?? "Unknown"}`);
  doc.text(`Architecture: ${fw?.architecture ?? "Unknown"}`);
  doc.text(`Scan Date: ${scan?.startedAt?.toISOString() ?? new Date().toISOString()}`);
  doc.text(`Risk Level: ${scan?.riskLevel?.toUpperCase() ?? "UNKNOWN"}`);
  doc.text(`Vulnerabilities Found: ${vulns.length}`);

  doc.moveDown();
  doc.fontSize(15).text("EXECUTIVE SUMMARY (AI — Google Gemini 2.5 Flash)");
  doc.moveDown(0.5);
  doc.fontSize(11).text(report?.summary ?? "No AI summary available.");

  doc.moveDown();
  doc.fontSize(15).text("KEY FINDINGS");
  doc.moveDown(0.5);
  doc.fontSize(11);
  if (keyFindings.length === 0) {
    doc.text("No key findings available.");
  } else {
    keyFindings.forEach((finding, index) => {
      doc.text(`${index + 1}. ${finding}`);
      doc.moveDown(0.25);
    });
  }

  doc.moveDown();
  doc.fontSize(15).text("RECOMMENDATIONS");
  doc.moveDown(0.5);
  doc.fontSize(11);
  if (recommendations.length === 0) {
    doc.text("No recommendations available.");
  } else {
    recommendations.forEach((recommendation, index) => {
      doc.text(`${index + 1}. ${recommendation}`);
      doc.moveDown(0.25);
    });
  }

  doc.moveDown();
  doc.fontSize(15).text("VULNERABILITIES");
  doc.moveDown(0.5);
  doc.fontSize(11);
  if (vulns.length === 0) {
    doc.text("No vulnerabilities found.");
  } else {
    vulns.forEach((v) => {
      doc.font("Helvetica-Bold").text(`[${v.severity.toUpperCase()}] ${v.type}`);
      doc.font("Helvetica");
      doc.text(`File: ${v.affectedFile}`);
      doc.text(`Description: ${v.description}`);
      doc.text(`Fix: ${v.recommendation}`);
      doc.moveDown();
    });
  }

  doc.moveDown();
  doc.fontSize(9).text("Generated by Viv Scanner", { align: "center" });

  doc.end();
  await finished;

  return { path: outPath, size: stream.bytesWritten };
}